$(document).ready(function(){
  let totalMarks;
  var questionOne, questionTwo, questionThree, questionFour, questionFive, questionSix, questionSeven, questionEight, questionNine, questionTen;
  $('#begin').click(function(){
    $('#question-1').show(350);
    $('#intro').hide(10);
  });
  $('#next1').click(function(){
    $('#question-2').show(350);
    $('#question-1').hide(10);
  })
  $('#next2').click(function(){
    $('#question-3').show(350);
    $('#question-2').hide(10);
  })
  $('#next3').click(function(){
    $('#question-4').show(350);
    $('#question-3').hide(10);
  });
  $('#next4').click(function(){
    $('#question-5').show(350);
    $('#question-4').hide(10);
  });
  $('#next5').click(function(){
    $('#question-6').show(350);
    $('#question-5').hide(10);
  });
  $('#next6').click(function(){
    $('#question-7').show(350);
    $('#question-6').hide(10);
  });
  $('#next7').click(function(){
    $('#question-8').show(350);
    $('#question-7').hide(10);
  });
  $('#next8').click(function(){
    $('#question-9').show(350);
    $('#question-8').hide(10);
  });
  $('#next9').click(function(){
    $('#question-10').show(350);
    $('#question-9').hide(10);
  });
    //Checking the results of the test.
  $('#results').click(function(){ //id introduction called results for the results button.
    $('#check').show(350);
    $('#question-10').hide(10);
  })
  /*__________________________________
    Question One
    __________________________________
  */
  $('#1a').click(function(){
    $('#question-two').show(215);
    $('#1aa').addClass('clicked')
    $('#1a').addClass('clicked')
    $('#1bb').removeClass('clicked')
    $('#1b').removeClass('clicked')
  });
  $('#1a').dblclick(function(){
    $('#question-two').hide(215);
    $('#1aa').removeClass('clicked')
    $('#1a').removeClass('clicked')
  });
  console.log(questionOne)
  $('#1b').click(function(){
    $('#question-two').show(215);
    $('#1bb').addClass('clicked')
    $('#1b').addClass('clicked')
    $('#1aa').removeClass('clicked')
    $('#1a').removeClass('clicked')
  });
  $('#1b').dblclick(function(){
    $('#question-two').hide(215);
    $('#1bb').removeClass('clicked')
    $('#1b').removeClass('clicked')
  });

  // trying to make a function that clicks the questions.
  /*__________________________________
    Question Two
    __________________________________
  */
  $('#2a').click(function(){
    $('#question-three').show(215);
    $('#2aa').addClass('clicked')
    $('#2a').addClass('clicked')
    $('#2bb').removeClass('clicked')
    $('#2b').removeClass('clicked')
    $('#2cc').removeClass('clicked')
    $('#2c').removeClass('clicked')
  });
  $('#2a').dblclick(function(){
    $('#question-three').hide(215);
    $('#2aa').removeClass('clicked')
    $('#2a').removeClass('clicked')
  });
  //answer two selection
  $('#2b').click(function(){
    $('#question-three').show(215);
    $('#2bb').addClass('clicked')
    $('#2b').addClass('clicked')
    $('#2aa').removeClass('clicked')
    $('#2a').removeClass('clicked')
    $('#2cc').removeClass('clicked')
    $('#2c').removeClass('clicked')
  });
  $('#2b').dblclick(function(){
    $('#question-three').hide(215);
    $('#2bb').removeClass('clicked')
    $('#2b').removeClass('clicked')
  });
  //answer three selection.
  $('#2c').click(function(){
    $('#question-three').show(215);
    $('#2cc').addClass('clicked')
    $('#2c').addClass('clicked')
    $('#2aa').removeClass('clicked')
    $('#2a').removeClass('clicked')
    $('#2bb').removeClass('clicked')
    $('#2b').removeClass('clicked')
  });
  $('#2c').dblclick(function(){
    $('#question-three').hide(215);
    $('#2cc').removeClass('clicked')
    $('#2c').removeClass('clicked')
  });
  /*__________________________________
    Question Three
    __________________________________
  */
  //selection of the first answer
  $('#3a').click(function(){
    $('#question-four').show(215);
    $('#3aa').addClass('clicked')
    $('#3a').addClass('clicked')
    $('#3bb').removeClass('clicked')
    $('#3b').removeClass('clicked')
    $('#3cc').removeClass('clicked')
    $('#3c').removeClass('clicked')
  });
  $('#3a').dblclick(function(){
    $('#question-four').hide(215);
    $('#3aa').removeClass('clicked')
    $('#3a').removeClass('clicked')
  });
  //answer two selection
  $('#3b').click(function(){
    $('#question-four').show(215);
    $('#3bb').addClass('clicked')
    $('#3b').addClass('clicked')
    $('#3aa').removeClass('clicked')
    $('#3a').removeClass('clicked')
    $('#3cc').removeClass('clicked')
    $('#3c').removeClass('clicked')
  });
  $('#3b').dblclick(function(){
    $('#question-four').hide(215);
    $('#3bb').removeClass('clicked')
    $('#3b').removeClass('clicked')
  });
  //answer three selection.
  $('#3c').click(function(){
    $('#question-four').show(215);
    $('#3cc').addClass('clicked')
    $('#3c').addClass('clicked')
    $('#3aa').removeClass('clicked')
    $('#3a').removeClass('clicked')
    $('#3bb').removeClass('clicked')
    $('#3b').removeClass('clicked')
  });
  $('#3c').dblclick(function(){
    $('#question-four').hide(215);
    $('#3cc').removeClass('clicked')
    $('#3c').removeClass('clicked')
  });
  /*__________________________________
    Question Four
    __________________________________
  */
  //selection of the first answer
  $('#4a').click(function(){
    $('#question-five').show(215);
    $('#4aa').addClass('clicked')
    $('#4a').addClass('clicked')
    $('#4bb').removeClass('clicked')
    $('#4b').removeClass('clicked')
    $('#4cc').removeClass('clicked')
    $('#4c').removeClass('clicked')
  });
  $('#4a').dblclick(function(){
    $('#question-five').hide(215);
    $('#4aa').removeClass('clicked')
    $('#4a').removeClass('clicked')
  });
  //answer two selection
  $('#4b').click(function(){
    $('#question-five').show(215);
    $('#4bb').addClass('clicked')
    $('#4b').addClass('clicked')
    $('#4aa').removeClass('clicked')
    $('#4a').removeClass('clicked')
    $('#4cc').removeClass('clicked')
    $('#4c').removeClass('clicked')
  });
  $('#4b').dblclick(function(){
    $('#question-five').hide(215);
    $('#4bb').removeClass('clicked')
    $('#4b').removeClass('clicked')
  });
  //answer three selection.
  $('#4c').click(function(){
    $('#question-five').show(215);
    $('#4cc').addClass('clicked')
    $('#4c').addClass('clicked')
    $('#4aa').removeClass('clicked')
    $('#4a').removeClass('clicked')
    $('#4bb').removeClass('clicked')
    $('#4b').removeClass('clicked')
  });
  $('#4c').dblclick(function(){
    $('#question-five').hide(215);
    $('#4cc').removeClass('clicked')
    $('#4c').removeClass('clicked')
  });
  /*__________________________________
    Question Five
    __________________________________
  */
  //selection of the first answer
  $('#4a').click(function(){
    $('#question-five').show(215);
    $('#4aa').addClass('clicked')
    $('#4a').addClass('clicked')
    $('#4bb').removeClass('clicked')
    $('#4b').removeClass('clicked')
    $('#4cc').removeClass('clicked')
    $('#4c').removeClass('clicked')
  });
  $('#4a').dblclick(function(){
    $('#question-five').hide(215);
    $('#4aa').removeClass('clicked')
    $('#4a').removeClass('clicked')
  });
  //answer two selection
  $('#4b').click(function(){
    $('#question-five').show(215);
    $('#4bb').addClass('clicked')
    $('#4b').addClass('clicked')
    $('#4aa').removeClass('clicked')
    $('#4a').removeClass('clicked')
    $('#4cc').removeClass('clicked')
    $('#4c').removeClass('clicked')
  });
  $('#4b').dblclick(function(){
    $('#question-five').hide(215);
    $('#4bb').removeClass('clicked')
    $('#4b').removeClass('clicked')
  });
  //answer three selection.
  $('#4c').click(function(){
    $('#question-five').show(215);
    $('#4cc').addClass('clicked')
    $('#4c').addClass('clicked')
    $('#4aa').removeClass('clicked')
    $('#4a').removeClass('clicked')
    $('#4bb').removeClass('clicked')
    $('#4b').removeClass('clicked')
  });
  $('#4c').dblclick(function(){
    $('#question-five').hide(215);
    $('#4cc').removeClass('clicked')
    $('#4c').removeClass('clicked')
  });
});
//The end of the code